name: goxel2
version: git
summary: A 3D Voxel Art Editor
description: |
  goxel2 is a cross-platform voxel art editor (3D images formed of cubes).
  It works on Linux, Windows and macOS & aims to improve from it's predecessor goxel

base: core20
grade: stable
confinement: classic

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  goxel:
    command: $SNAP/goxel2
    plugs:
      - x11
      - opengl
      - home

parts:
  goxel:
    source: .
    plugin: nil
    override-build: |
      make release
    build-packages: [clang, make, scons, pkg-config, libglfw3-dev, libgtk-3-dev, libpng12-dev]
