name: goxel2
version: git
summary: A 3D Voxel Art Editor
description: |
  You can use goxel2 to create voxel graphics (3D images formed of cubes). 
  It works on Linux, Windows and macOS.

confinement: strict

apps:
  goxel:
    command: desktop-launch $SNAP/goxel2
    plugs:
      - x11
      - opengl
      - home

parts:
  goxel:
    after: [desktop-gtk3]
    source: .
    plugin: make
    build: |
      make release
    install: |
      cp goxel2 $SNAPCRAFT_PART_INSTALL
      cp icon.png $SNAPCRAFT_PART_INSTALL
    build-packages:
      - scons
      - pkg-config
      - libglfw3-dev
      - libgtk-3-dev
      - libpng12-dev
