name: Publish On AUR
on: 
  workflow_dispatch:
    inputs: 
      version: 
        type: text
        description: 'Version number Eg: 4.2.0' 

jobs:
  Publish-On-AUR:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set PKGBUILD Version
      run: sed -i 's/${VERSION_OF_PROGRAM}/${{github.event.inputs.version}}/g' scripts/arch/PKGBUILD

    - name: Publish AUR package
      uses: KSXGitHub/github-actions-deploy-aur@v2.3.0
      with:
        pkgname: goxel2-git
        pkgbuild: ./scripts/arch/PKGBUILD
        commit_username: ${{ secrets.AUR_USERNAME }}
        commit_email: ${{ secrets.AUR_EMAIL }}
        ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        commit_message: Update AUR package
        force_push: 'true'
        ssh_keyscan_types: rsa,dsa,ecdsa,ed25519

# NOTE - This Workflow is only meant to run after the release.yml has been run successfully
