name: nightly
on:
  push:
    branches: [ master ]

jobs:
  Generate-Assets:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Generate Assets
      run: |
        python3 tools/create_assets.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: generated_assets
        path: ./src/assets/
        if-no-files-found: error

  Build-For-Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-glfw mingw-w64-x86_64-libtre-git scons make git

      - name: Download Assets
        uses: actions/download-artifact@v2
        with:
          name: generated_assets

      - name: Build Goxel
        run: |
          make release
          mv goxel2.exe goxel2-win32.exe

  Build-For-Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Install GLFW3, PKG Config, Git, Gtk3-dev & SCONS
      run: |
        sudo apt-get install libglfw3-dev pkg-config git libgtk-3-dev scons

    - name: Download Assets
      uses: actions/download-artifact@v2
      with:
        name: generated_assets

    - name: Build Goxel
      run: make release

  Build-For-OSX:
    runs-on: macos-11
    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Download Assets
      uses: actions/download-artifact@v2
      with:
        name: generated_assets

    - name: Build Goxel
      run: cd osx/goxel && xcodebuild -configuration "Release" -destination 'platform=macOS' build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO && cd ../..

  Success:
    if: ${{ always() }}
    needs: [Build-For-Linux, Build-For-OSX, Build-For-Windows]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
