name: nightly
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  windows_x86_64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-glfw mingw-w64-x86_64-libtre-git mingw-w64-x86_64-cmake mingw-w64-x86_64-libpng scons make git

      - name: Build Goxel
        run: |
          make lua
          make release

  windows_i686:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-i686-gcc mingw-w64-i686-glfw mingw-w64-i686-libtre-git mingw-w64-i686-cmake mingw-w64-i686-libpng scons make

      - name: Build Goxel
        run: |
          export PATH=/mingw32/bin/:$PATH
          make lua
          make release

  linux_x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install GLFW3, PKG Config, Git, Gtk3, LibPNG & SCONS
      run: |
        sudo apt-get install libglfw3-dev pkg-config git libgtk-3-dev libpng-dev libpng16-16 scons

    - name: Build Goxel
      run: |
        make lua
        make release

  linux_i686:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Ubuntu 18.04 x86
      uses: paulproteus/ubuntu-18.04-x86@0.1
      with:
        command: |
          apt-get update -y
          apt-get install -y snap libglfw3-dev pkg-config git libgtk-3-dev libpng-dev libpng16-16 scons
          snap install cmake --classic
          make lua
          make release

    - name: Exit if file not exists
      run: |
        if [ ! -e ./goxel2 ]; then
            echo "goxel2 executable not found"
            exit 1
        fi

  osx_x86_64:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Scons
      run: brew install scons

    - name: Build Lua
      run: |
        cd lib/lua-5.4.4/
        cmake -B build
        cmake --build build
        cd ../../

    - name: Build Goxel
      run: cd osx/goxel && xcodebuild -configuration "Release" -destination 'platform=macOS' build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO && cd ../..

  Success:
    needs: [linux_x86_64, linux_i686, osx_x86_64, windows_x86_64, windows_i686]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
